[project]
name = "brother_label_printer_control"
version = "1.0.0"
description = "A library for creating and printing labels for Brother P-Touch devices"
authors = [
    { name = "Adrian Tschira", email = "packages@notafile.com" },
    { name = "Benedikt Neuffer", email = "benedikt.neuffer@kit.edu" },
    { name = "Ben Burwood", email = "ben.burwood@outlook.com" },
]
license = "Apache-2.0"
readme = "README.md"
dependencies = [
    "packbits>=0.6",
    "pillow>=12.3.0",
    "pyusb>=1.3.1",
]

[dependency-groups]
bluetooth = [
    "pyserial>=3.5",
]
qrcode = [
    "qrcode>=8.2",
]
snmp = [
    "pyasn1>=0.6.4",
    "pysnmp>=7.1.29",
]

[build-system]
requires = ["uv_build>=0.12.7,<0.13"]
build-backend = "uv_build"

[tool.ruff]
line-length = 150
